## 개발모드와 운영모드 나누기
application:
  version: v0.0.1
  title: idden portfolio

spring:
 profiles:
   active: dev
---


## \ub370\uc774\ud130\ubca0\uc774\uc2a4 \uc124\uc815
spring:
  profiles: dev
  datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/dw_501
     username: root
     password: 1234
  jpa:
     database: mysql
     generate-ddl: true
     hibernate:
       ddl-auto: update
     open-in-view: false  # 이거 내가 추가한 
     show-sql: true
     properties:
       hibernate:
          format_sql: true


---
spring:
  profiles: env
  datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://database-1.ctci74b4ljqg.ap-northeast-2.rds.amazonaws.com/dw_501
     username: apple
     password: 1234
  jpa:
     database: mysql
     generate-ddl: true
     hibernate:
       ddl-auto: update
     open-in-view: false  # 이거 내가 추가한 
     show-sql: true
     properties:
       hibernate:
          format_sql: true